version: '3'

services:
  sqlserver-compose:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Teste123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - mssql-compose-network
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver-compose
    volumes:
      - ./Volume_MSSQL:/var/opt/mssql
  
  mssql-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "teste"
    ports:
      - "81:80"
    depends_on:
      - sqlserver-compose
    networks:
      - mssql-compose-network

networks:
  mssql-compose-network:
    driver: bridge